const D=window.LATIN_DATA,app=document.querySelector('#app');
const KEY='learnLatin.v1';
const FIREBASE_CONFIG={apiKey:'AIzaSyDrreK9rhsoOpIYNr4QeNZ7CsXgQiMPW0E',authDomain:'kk-syllabus.firebaseapp.com',projectId:'kk-syllabus',storageBucket:'kk-syllabus.firebasestorage.app',messagingSenderId:'821660665663',appId:'1:821660665663:web:c708860329bb97dc24758a'};
const OWNER_UID='2AJSfYdtg5URWHv7HCzpNMmKIlg2';
const blank={sessions:[],mastery:{},due:{},introduced:['roles'],settings:{name:'Sai',learnerCode:'sai-latin'},lastDate:null,streak:0};
let firebaseApi=null,firebaseAuth=null,firebaseDb=null;
let state=load(),quiz=null;
function load(){try{return {...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(blank)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateStreak();syncLatest().catch(()=>{});}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function shuffle(a){let x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function pct(n,d){return d?Math.round(n/d*100):0}function fmt(ms){return ms<1000?`${ms} ms`:`${(ms/1000).toFixed(1)} s`}
function allAttempts(){return state.sessions.flatMap(s=>s.answers||[])}
function updateStreak(){document.querySelector('#streakBadge').textContent=`🔥 ${state.streak||0} day${state.streak===1?'':'s'}`}
function nav(route){document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route))}
function route(){const raw=location.hash.slice(1)||'home', [r,id]=raw.split('/');nav(['lesson','worksheet','plan','glossary','sync','replay'].includes(r)?'more':r);({home,learn,practice,progress,more,lesson,worksheet,plan,glossary,sync,replay}[r]||home)(id);scrollTo(0,0);app.focus({preventScroll:true})}
function home(){const a=allAttempts(),correct=a.filter(x=>x.correct).length,due=Object.values(state.due).filter(x=>x<=Date.now()).length;app.innerHTML=`<section class="hero"><p class="eyebrow" style="color:#f5cf72">Dad + Sai Latin</p><h1>Read the endings.<br>Solve the sentence.</h1><p class="lede">Today: a short retrieval round, one clear grammar idea, then tiny-sentence translation.</p><div class="actions"><a class="btn primary" href="#practice">Start 10 questions</a><a class="btn secondary" href="#learn">Learn a concept</a></div></section><section class="grid"><article class="card third"><p class="eyebrow">Due now</p><div class="metric">${due||Math.min(6,D.questions.length)}</div><p class="muted">spaced-repetition questions</p></article><article class="card third"><p class="eyebrow">Accuracy</p><div class="metric">${pct(correct,a.length)}%</div><p class="muted">across ${a.length} answers</p></article><article class="card third"><p class="eyebrow">Sessions</p><div class="metric">${state.sessions.length}</div><p class="muted">completed together</p></article><article class="card wide"><h2>The one idea to remember</h2><p class="lede">English mainly uses position. Latin puts job labels on word endings. So first find each word's role, then build natural English.</p><div class="example"><b>puerum puella amat</b> → The girl loves the boy.</div></article><article class="card"><h2>Your route</h2><p>Follow the six foundations first, then verbs and translation.</p><a class="btn" href="#learn">View lessons</a></article><article class="card"><h2>This week's plan</h2><p>Four short sessions beat one long session. Aim for 10–15 minutes, four times a week.</p><a class="btn ghost" href="#plan">See suggested timings</a></article></section>`}
function learn(){app.innerHTML=`<p class="eyebrow">Grammar guide</p><h1>Latin's machinery, in plain English</h1><p class="lede">Learn the role first, then its Latin label. Lessons 1–6 are the foundations to cover before school reaches them.</p><div class="lesson-list">${D.topics.map(t=>`<a class="lesson-card" href="#lesson/${t.id}"><span class="lesson-num">${t.n}</span><span><h3>${t.title}</h3><p>${t.short} · ${t.minutes} min</p></span></a>`).join('')}</div>`}
function lesson(id){const t=D.topics.find(x=>x.id===id)||D.topics[0];state.introduced=[...new Set([...(state.introduced||['roles']),t.id])];localStorage.setItem(KEY,JSON.stringify(state));app.innerHTML=`<a href="#learn">← All lessons</a><p class="eyebrow">Lesson ${t.n} · ${t.minutes} minutes</p><h1>${t.title}</h1><p class="lede">${t.summary}</p><article class="card wide">${t.body}<div class="actions"><button class="btn" id="lessonPractice">Practise only this lesson</button><a class="btn ghost" href="#lesson/${D.topics[Math.min(t.n,D.topics.length-1)].id}">${t.n===D.topics.length?'Start again':'Next lesson'} →</a></div></article>`;document.querySelector('#lessonPractice').onclick=()=>startQuiz(t.id,10)}
function topicEvidence(id){const a=allAttempts().filter(x=>x.topic===id).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)),recent=a.slice(-12);return {answers:a.length,accuracy:pct(recent.filter(x=>x.correct&&!x.supported).length,recent.length),avg:recent.length?recent.reduce((s,x)=>s+x.ms,0)/recent.length:Infinity}}
function guidedTopic(){if(roleStageIndex()<D.roleStages.length)return 'roles';for(const t of D.topics.filter(t=>t.id!=='roles')){const e=topicEvidence(t.id);if(e.answers<8||e.accuracy<85)return t.id}return D.topics.at(-1).id}
function practice(){const due=Object.values(state.due).filter(x=>x<=Date.now()).length,current=D.topics.find(t=>t.id===guidedTopic()),known=(state.introduced||[]).includes(current.id);app.innerHTML=`<p class="eyebrow">Gentle, adaptive practice</p><h1>Continue from what you know</h1><div class="grid"><article class="card wide"><p class="eyebrow">Recommended next</p><h2>${current.title}</h2><p>${known?'Stay here while the idea becomes accurate and fluent.':'This is the next small idea. Read its short explanation before any questions appear.'} Nothing later will appear without preparation.</p><button class="btn" id="guidedStart">${known?'Continue my path':'Learn this idea first'}</button></article><article class="card"><h2>Review learned material</h2><p>${due||'A few'} questions due from lessons you have already opened. Weak and slow items return sooner.</p><button class="btn" data-mode="review">Review familiar topics</button></article><article class="card"><h2>Speed check</h2><p>Uses only introduced topics. Accuracy comes first; timing shows what is not automatic yet.</p><button class="btn" data-mode="speed">Start familiar speed check</button></article><article class="card wide"><h2>Choose one lesson</h2><div class="form-group"><label for="topicPick">Topic</label><select id="topicPick">${D.topics.map(t=>`<option value="${t.id}">${t.title}${(state.introduced||[]).includes(t.id)?' · introduced':' · learn first'}</option>`).join('')}</select></div><button class="btn" id="focusStart">Open its lesson first</button></article></div>`;document.querySelector('#guidedStart').onclick=()=>known?startQuiz('adaptive',10):location.hash=`lesson/${current.id}`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startQuiz(b.dataset.mode,b.dataset.mode==='speed'?20:10));document.querySelector('#focusStart').onclick=()=>location.hash=`lesson/${document.querySelector('#topicPick').value}`}
function startQuiz(mode,count){
 const introduced=state.introduced||['roles'];let pool;
 const topic=mode==='adaptive'?guidedTopic():mode;
 if(mode==='review'||mode==='speed')pool=D.questions.filter(q=>introduced.includes(q.topic));else pool=D.questions.filter(q=>q.topic===topic);
 const stage=D.roleStages[Math.min(roleStageIndex(),D.roleStages.length-1)];
 pool=pool.filter(q=>q.topic!=='roles'||q.skill===stage.id);
 const recent=allAttempts().sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).slice(0,12);
 const recentIds=new Set(recent.map(a=>a.sentenceId||a.questionId));
 const candidates=shuffle(pool).sort((a,b)=>Number(recentIds.has(a.sentenceId||a.id))-Number(recentIds.has(b.sentenceId||b.id))||Number((state.due[a.id]||0)>Date.now())-Number((state.due[b.id]||0)>Date.now()));
 const seen=new Set(),qs=candidates.filter(q=>{const key=q.sentenceId||q.id;if(seen.has(key))return false;seen.add(key);return true}).slice(0,count);
 if(!qs.length){app.innerHTML='<h1>Nothing due here yet</h1><a href="#learn">Choose a lesson</a>';return}
 quiz={id:crypto.randomUUID(),mode,questions:qs,i:0,answers:[],started:Date.now(),confidence:2};
 nav('practice');if(qs[0].topic==='roles'){app.innerHTML=`<section class="question quiz-shell"><p class="eyebrow">One small idea</p><h1>${esc(stage.title)}</h1><p class="lede">${esc(stage.help)}</p><p>Try ${qs.length} different sentences. Accuracy first; there is no speed limit.</p><button class="btn" id="beginRound">Let's try</button></section>`;document.querySelector('#beginRound').onclick=renderQuestion;}else renderQuestion();
}
function renderQuestion(){
 if(!quiz)return;
 const upcoming=quiz.questions[quiz.i];
 if(upcoming.topic!=='roles'&&!state.mastery[upcoming.id]&&!quiz.teachingShown){quiz.teachingShown=true;app.innerHTML=`<section class="question quiz-shell"><p class="eyebrow">Meet this idea first</p><h1>A small step</h1><p class="lede">${esc(upcoming.e)}</p><p>Useful answer or vocabulary: <b>${esc(upcoming.a)}</b></p><p>This first supported try is for learning, not proof of mastery.</p><button class="btn" id="tryNew">Try it with me</button></section>`;document.querySelector('#tryNew').onclick=renderQuestion;return;}
 const q=quiz.questions[quiz.i];quiz.answered=false;quiz.supported=!!quiz.teachingShown;quiz.teachingShown=false;quiz.confidence=2;quiz.hiddenMs=0;quiz.hiddenAt=null;
 app.innerHTML=`<div class="quiz-shell"><div class="quiz-head"><button class="btn ghost" id="exitRound">Finish for now</button><span>${quiz.i+1} of ${quiz.questions.length}</span></div><p class="eyebrow">${esc(D.topics.find(t=>t.id===q.topic)?.title)}</p><section class="question"><h2>${esc(q.q)}</h2>${q.tokens?`<div class="sentence-words" aria-label="Sentence">${q.tokens.map((t,i)=>`<button class="word-button" data-token="${i}">${esc(t.word)}</button>`).join('')}<span>.</span></div>`:`<div class="answers">${shuffle([q.a,...q.o]).map(x=>`<button class="answer" data-answer="${esc(x)}">${esc(x)}</button>`).join('')}</div>`}<div class="actions"><button class="btn ghost" id="hintBtn">Help me</button><button class="btn ghost" id="readBtn">Read aloud</button></div><p id="wordHelp" class="explain" role="status"></p><div id="answerFeedback" aria-live="polite"></div></section></div>`;
 quiz.shown=performance.now();
 document.querySelector('#exitRound').onclick=()=>{snapshotSession(false);quiz=null;location.hash='progress';progress()};
 document.querySelector('#hintBtn').onclick=()=>{quiz.supported=true;document.querySelector('#wordHelp').textContent=q.hint||q.e};
 document.querySelector('#readBtn').onclick=()=>{quiz.supported=true;if(!('speechSynthesis' in window)){document.querySelector('#wordHelp').textContent='Read aloud is unavailable on this device. Ask a grown-up to read with you.';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.q+' '+(q.sentence||''));u.lang='en-GB';u.rate=.85;speechSynthesis.speak(u)};
 document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{const t=q.tokens[+b.dataset.token];document.querySelector('#wordHelp').textContent=t.why;if(!quiz.answered)answer(q,{dataset:{answer:t.word}})});
 document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(q,b));
}
function answer(q,b){
 if(quiz.answered)return;quiz.answered=true;
 const ms=Math.max(0,Math.round(performance.now()-quiz.shown-quiz.hiddenMs)),chosen=b.dataset.answer,correct=(q.accepted||[q.a]).includes(chosen);
 document.querySelectorAll('.answer').forEach(x=>{x.disabled=true;x.classList.toggle('correct',x.dataset.answer===q.a);x.classList.toggle('wrong',x.dataset.answer===chosen&&!correct)});
 if(q.tokens)document.querySelectorAll('[data-token]').forEach(x=>{const t=q.tokens[+x.dataset.token];x.classList.add('pos-'+t.pos);x.innerHTML=esc(t.word)+'<small>'+esc(t.pos)+(t.role?' · '+esc(t.role):'')+'</small>';x.setAttribute('aria-label',t.word+': '+t.pos+(t.role?', '+t.role:''));});
 quiz.answers.push({questionId:q.id,sentenceId:q.sentenceId||q.id,skill:q.skill||null,topic:q.topic,question:q.q+(q.sentence?' '+q.sentence:''),chosen,correctAnswer:(q.accepted||[q.a]).join(' or '),correct,ms,supported:quiz.supported,confidence:quiz.confidence,at:new Date().toISOString()});
 const prior=state.mastery[q.id]||{score:0,seen:0};prior.seen++;prior.score=Math.max(0,Math.min(5,prior.score+(correct&&!quiz.supported?1:-1)));state.mastery[q.id]=prior;
 state.due[q.id]=Date.now()+(correct&&!quiz.supported?[1,2,4,8,16,30][prior.score]:.02)*86400000;
 snapshotSession(false);showFeedback(q,correct,ms);
}
function showFeedback(q,correct,ms){document.querySelector('#answerFeedback').innerHTML=`<h3 class="${correct?'success':'danger'}">${correct?'Yes!':'Let’s look together.'}</h3><p>${esc(q.e)}</p>${!correct?`<p>Look for: <b>${esc((q.accepted||[q.a]).join(' or '))}</b>.</p>`:''}<p class="muted">${fmt(ms)} · Saved in Progress${quiz.supported?' · with help':''}. Take the time you need.</p>${q.tokens?'<p>Tap any coloured word to explore its type and sentence job.</p>':''}<button class="btn" id="continueBtn">${quiz.i+1===quiz.questions.length?'See my progress':'Next sentence'}</button>`;document.querySelector('#continueBtn').onclick=()=>{quiz.i++;quiz.i>=quiz.questions.length?finishQuiz():renderQuestion()}}
function finishQuiz(){snapshotSession(true);quiz=null;location.hash='progress';progress()}
function progress(){
 const attempts=allAttempts().sort((a,b)=>Date.parse(b.at)-Date.parse(a.at));
 app.innerHTML=`<p class="eyebrow">Every answer counts</p><h1>Progress</h1><p>Answers save immediately, even if you stop mid-round. Times include reading and thinking, not time with this tab hidden. Speed is not a pass/fail test.</p><div class="grid"><article class="card"><div class="metric">${attempts.length}</div><p>answers saved</p></article><article class="card"><div class="metric">${pct(attempts.filter(a=>a.correct).length,attempts.length)}%</div><p>correct</p></article></div><h2>Topic and question detail</h2><label for="statsTopic">Show topic</label><select id="statsTopic"><option value="">All topics</option>${D.topics.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select><div id="statsDetails"></div><h2>Sessions, including unfinished rounds</h2>${state.sessions.map(s=>`<div class="session-row"><span>${new Date(s.startedAt).toLocaleString()} · ${s.completed===false?'Partial round':'Completed'}</span><span>${s.correct}/${s.total} correct</span><a href="#replay/${esc(s.id)}">Question history / replay</a></div>`).join('')||'<p>Your first answer will appear here.</p>'}`;
 const render=()=>{const list=attempts.filter(a=>!document.querySelector('#statsTopic').value||a.topic===document.querySelector('#statsTopic').value);document.querySelector('#statsDetails').innerHTML=`<p>${list.length} answers · ${pct(list.filter(a=>a.correct).length,list.length)}% correct · ${list.length?fmt(Math.round(list.reduce((s,a)=>s+a.ms,0)/list.length)):'—'} average</p>${list.map(a=>`<details class="attempt-detail"><summary>${a.correct?'✓':'Try again'} ${esc(a.question)} — ${fmt(a.ms)}</summary><p>Your answer: ${esc(a.chosen)}. Accepted answer(s): ${esc(a.correctAnswer)}.</p><p>${new Date(a.at).toLocaleString()} · ${a.supported?'With help':'Independent answer'}</p></details>`).join('')}`};document.querySelector('#statsTopic').onchange=render;render();
}
function replay(id){const s=state.sessions.find(x=>x.id===id);if(!s){location.hash='progress';return}app.innerHTML=`<a href="#progress">← Progress</a><p class="eyebrow">Session replay</p><h1>${new Date(s.startedAt).toLocaleString()}</h1><p class="lede">${s.correct}/${s.total} correct · ${fmt(s.avgMs)} average. Replay uses the same question set with answer positions reshuffled.</p><article class="card wide">${s.answers.map((a,i)=>`<div class="session-row"><span>${i+1}. ${a.question}<br><small>${a.correct?'Answered correctly':`Answered “${esc(a.chosen)}”; correct: “${esc(a.correctAnswer)}”`}</small></span><b>${fmt(a.ms)}</b><span>confidence ${a.confidence}/3</span></div>`).join('')}<button class="btn" id="replayBtn">Replay these questions</button></article>`;document.querySelector('#replayBtn').onclick=()=>{const qs=s.answers.map(a=>D.questions.find(q=>q.id===a.questionId)).filter(Boolean);quiz={mode:'replay',questions:qs,i:0,answers:[],started:Date.now(),shown:Date.now(),confidence:2};renderQuestion()}}
function plan(){const weeks=[['Week 1','Roles + endings','4 × 10 min'],['Week 2','Cases','4 × 12 min'],['Week 3','Agreement + verbs','4 × 15 min'],['Week 4','Tenses + tiny translation','4 × 15 min']];app.innerHTML=`<p class="eyebrow">Suggested timings</p><h1>Stay 6–10 weeks ahead, not years ahead</h1><p class="lede">The aim is familiarity before class: “I recognise this” rather than rushing through the school syllabus.</p><article class="card wide"><h2>Four-week head start</h2>${weeks.map(w=>`<div class="plan-day"><b>${w[0]}</b><span>${w[1]}</span><span class="tag">${w[2]}</span></div>`).join('')}</article><div class="grid"><article class="card"><h2>A normal 12-minute session</h2><ol><li>2 min: due vocabulary/grammar</li><li>3 min: one idea</li><li>5 min: 3–5 tiny sentences</li><li>2 min: explain “how do you know?”</li></ol></article><article class="card"><h2>When is it mastered?</h2><p>Use three signals together: at least 85% accuracy, correct answers mostly below 4 seconds, and success after gaps of several days. Fast guessing is not mastery.</p></article><article class="card wide"><h2>After the first month</h2><p>Continue 3–4 short sessions weekly. Add the vocabulary and sequence from Sai's actual school textbook when known. Keep one playful “Sai catches Dad's mistake” round each week.</p><a class="btn" href="#practice">Start today's round</a></article></div>`}
function glossary(){app.innerHTML=`<p class="eyebrow">Core grammar terms</p><h1>Glossary</h1><div class="grid">${Object.entries(D.glossary).map(([k,v])=>`<article class="card"><h3>${k}</h3><p>${v}</p></article>`).join('')}</div>`}
function worksheet(){app.innerHTML=`<div class="no-print actions"><button class="btn" onclick="print()">Print worksheet</button><a class="btn ghost" href="assets/latin-six-foundations-worksheet.pdf" download>Download PDF</a></div><p class="eyebrow">Dad + Sai · six foundations</p><h1>Latin Grammar Head-Start Worksheet</h1><p>Name: ____________________ &nbsp; Date: ____________</p>${[['1. Word roles',['Underline the subject and circle the object: The enormous furry dog chased the frightened little cat.','Label S, V and O: Marcus carries the water.','Write your own subject–verb–object sentence.']],['2. Endings are role labels',['puella puerum amat. Who loves whom? Explain which endings helped.','puerum puella amat. Has the meaning changed? Why?']],['3. High-frequency words',['Match: puer, puella, aqua, via, amicus with girl, road, boy, friend, water.','Translate: puella aquam portat.']],['4. English grammar',['Define noun, verb and adjective in your own words.','In “The small dog runs quickly”, identify the adjective and adverb.']],['5. Word families',['Write one English relative of each: aqua, video, audio, porto.','What might “portable” have to do with porto (I carry)?']],['6. Tiny translations',['canis currit.','puer canem videt.','puella aquam portat.','Explain how an ending helped you solve one sentence.']]].map((s,i)=>`<article class="card wide ${i===3?'page-break':''}"><h2>${s[0]}</h2>${s[1].map((q,j)=>`<p><b>${j+1}.</b> ${q}</p><div class="worksheet-answer"></div>`).join('')}</article>`).join('')}<article class="card wide page-break"><h2>Parent/teacher answer guide</h2><p><b>1:</b> subject “The enormous furry dog”; object “the frightened little cat”. Marcus=S, carries=V, water=O.</p><p><b>2:</b> The girl loves the boy in both. -a / puella is nominative; -um / puerum is accusative.</p><p><b>3:</b> boy, girl, water, road, friend. The girl carries water.</p><p><b>4:</b> small is adjective; quickly is adverb.</p><p><b>5:</b> e.g. aquatic, visible/video, audible/audio, portable/transport. Portable means able to be carried.</p><p><b>6:</b> The dog runs. The boy sees the dog. The girl carries water.</p></article>`}
function more(){app.innerHTML=`<p class="eyebrow">Resources</p><h1>More</h1><div class="lesson-list"><a class="lesson-card" href="#plan"><span class="lesson-num">◷</span><span><h3>Study plan & timings</h3><p>What to learn, how long and when</p></span></a><a class="lesson-card" href="#worksheet"><span class="lesson-num">✎</span><span><h3>Six-foundations worksheet</h3><p>Interactive print view + downloadable PDF</p></span></a><a class="lesson-card" href="#glossary"><span class="lesson-num">Aa</span><span><h3>Core grammar glossary</h3><p>Case, declension, agreement and more</p></span></a><a class="lesson-card" href="#sync"><span class="lesson-num">↻</span><span><h3>Sync & data</h3><p>Connect the shared Firebase project or export progress</p></span></a></div>`}
function sync(){app.innerHTML=`<p class="eyebrow">Sync & data</p><h1>Keep progress safe</h1><article class="card wide"><div class="callout">This uses the same <b>kk-syllabus</b> Firebase project and owner-only access rules as the KKSyllabus app. Progress also remains on this device for offline use.</div><div class="form-group"><label for="learnerName">Learner name</label><input id="learnerName" value="${esc(state.settings.name)}"></div><div class="form-group"><label for="parentEmail">Parent Firebase email</label><input id="parentEmail" type="email" autocomplete="username"></div><div class="form-group"><label for="parentPassword">Password</label><input id="parentPassword" type="password" autocomplete="current-password"></div><div class="actions"><button class="btn" id="saveSync">Sign in & sync</button><button class="btn ghost" id="syncNow">Sync now</button><button class="btn ghost" id="disconnect">Disconnect</button><button class="btn ghost" id="exportData">Export progress</button><label class="btn secondary">Import progress<input type="file" id="importData" accept="application/json" hidden></label></div><p id="syncStatus" class="muted">Checking connection…</p></article>`;const status=document.querySelector('#syncStatus');firebaseReady().then(()=>{status.textContent=firebaseAuth.currentUser?'Connected to Firebase.':'Saved locally. Sign in to enable cloud sync.'}).catch(()=>status.textContent='Firebase is unavailable; local saving still works.');document.querySelector('#saveSync').onclick=async()=>{state.settings.name=document.querySelector('#learnerName').value.trim()||'Sai';localStorage.setItem(KEY,JSON.stringify(state));status.textContent='Connecting…';try{await connectFirebase(document.querySelector('#parentEmail').value,document.querySelector('#parentPassword').value);document.querySelector('#parentPassword').value='';await syncLatest(true);status.textContent='Connected and synced.';status.className='success'}catch(e){status.textContent=`Not connected: ${friendlyFirebaseError(e)}`;status.className='danger'}};document.querySelector('#syncNow').onclick=async()=>{status.textContent='Syncing…';try{await syncLatest(true);status.textContent='Synced.';status.className='success'}catch(e){status.textContent=friendlyFirebaseError(e);status.className='danger'}};document.querySelector('#disconnect').onclick=async()=>{await firebaseReady();await firebaseApi.signOut(firebaseAuth);status.textContent='Disconnected. Progress remains on this device.'};document.querySelector('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='learn-latin-progress.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#importData').onchange=async e=>{try{state={...blank,...JSON.parse(await e.target.files[0].text())};save();location.hash='progress'}catch{alert('That file is not a valid Learn Latin export.')}}}
async function firebaseReady(){if(firebaseApi)return;const [A,Auth,F]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);const fb=A.getApps()[0]||A.initializeApp(FIREBASE_CONFIG);firebaseAuth=Auth.getAuth(fb);firebaseDb=F.getFirestore(fb);firebaseApi={...Auth,...F};await firebaseAuth.authStateReady()}
function friendlyFirebaseError(e){const c=e?.code||'';if(c.includes('permission-denied'))return 'Cloud access was denied. Check that the KKSyllabus Firestore rules are published.';if(c.includes('invalid-credential')||c.includes('wrong-password')||c.includes('user-not-found'))return 'The email or password did not match.';if(c.includes('operation-not-allowed'))return 'Enable Email/Password sign-in in Firebase Authentication.';return e?.message||'Cloud sync could not finish; local work is safe.'}
async function connectFirebase(email,password){await firebaseReady();await firebaseApi.setPersistence(firebaseAuth,firebaseApi.browserLocalPersistence);const result=await firebaseApi.signInWithEmailAndPassword(firebaseAuth,email,password);if(result.user.uid!==OWNER_UID){await firebaseApi.signOut(firebaseAuth);throw Error('This is not the configured parent account.')}}
let syncRunning=false,syncAgain=false;
async function syncLatest(force=false){
 if(!navigator.onLine&&!force)return;
 if(syncRunning){syncAgain=true;return}
 syncRunning=true;
 try{
 await firebaseReady();
 if(!firebaseAuth.currentUser){if(force)throw Error('Sign in with the parent Firebase account first.');return}
 if(firebaseAuth.currentUser.uid!==OWNER_UID)throw Error('This is not the configured parent account.');
 const base=['families',OWNER_UID,'learners',state.settings.learnerCode],ref=firebaseApi.doc(firebaseDb,...base,'progress','latin');
 const merged=await firebaseApi.runTransaction(firebaseDb,async tx=>{
 const snap=await tx.get(ref),remote=snap.exists()?snap.data():{},sessions=new Map();
 for(const s of [...(remote.sessions||[]),...state.sessions]){const previous=sessions.get(s.id);if(!previous||(s.total||0)>(previous.total||0)||Date.parse(s.updatedAt||s.endedAt||s.startedAt)>=Date.parse(previous.updatedAt||previous.endedAt||previous.startedAt))sessions.set(s.id,s)}
 const next={version:2,sessions:[...sessions.values()].sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt)).slice(0,200),introduced:[...new Set([...(remote.introduced||[]),...(state.introduced||['roles'])])],mastery:{...(remote.mastery||{}),...state.mastery},due:{...(remote.due||{}),...state.due},lastDate:state.lastDate,streak:state.streak};
 tx.set(ref,{...next,updatedAt:firebaseApi.serverTimestamp()},{merge:true});return next;
 });
 // Do not replace answers recorded while a cloud transaction was in flight.
 const sessions=new Map(merged.sessions.map(s=>[s.id,s]));for(const s of state.sessions){const old=sessions.get(s.id);if(!old||s.total>=old.total)sessions.set(s.id,s)}
 state.sessions=[...sessions.values()].sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt));state.introduced=merged.introduced;
 localStorage.setItem(KEY,JSON.stringify(state));
 }finally{syncRunning=false;if(syncAgain){syncAgain=false;void syncLatest().catch(()=>{})}}
}
function roleStageIndex(){return D.roleStages.findIndex(stage=>{const a=allAttempts().filter(x=>x.skill===stage.id).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-10);return a.length<8||a.filter(x=>x.correct&&!x.supported).length/a.length<.85;})<0?D.roleStages.length:D.roleStages.findIndex(stage=>{const a=allAttempts().filter(x=>x.skill===stage.id).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-10);return a.length<8||a.filter(x=>x.correct&&!x.supported).length/a.length<.85;})}
function snapshotSession(completed){if(!quiz?.answers.length)return;quiz.id ||= crypto.randomUUID();const s={id:quiz.id,mode:quiz.mode,startedAt:new Date(quiz.started).toISOString(),updatedAt:new Date().toISOString(),completed,correct:quiz.answers.filter(a=>a.correct).length,total:quiz.answers.length,avgMs:Math.round(quiz.answers.reduce((n,a)=>n+a.ms,0)/quiz.answers.length),answers:[...quiz.answers]};const i=state.sessions.findIndex(x=>x.id===s.id);if(i<0)state.sessions.unshift(s);else state.sessions[i]=s;save()}
document.addEventListener('visibilitychange',()=>{if(!quiz||quiz.answered)return;if(document.hidden)quiz.hiddenAt=performance.now();else if(quiz.hiddenAt!=null){quiz.hiddenMs+=performance.now()-quiz.hiddenAt;quiz.hiddenAt=null}});
addEventListener('hashchange',()=>{quiz=null;route()});updateStreak();route();
