const config=document.querySelector('script[data-repository]');
const repo=config?.dataset.repository||'nirav2000/LearnLatin',version=config?.dataset.version||'4.1.0',key='app-notes:'+repo;
let releases=[];fetch('./release-notes.json').then(r=>r.json()).then(x=>{releases=x;window.dispatchEvent(new Event('latin-notes-changed'))}).catch(()=>{});
const normal=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');
function resolution(n){return releases.flatMap(r=>r.notes.map(note=>({...note,version:r.version,sourceVersion:note.sourceVersion||r.sourceVersion}))).find(r=>(!r.sourceVersion||n.version===r.sourceVersion)&&normal(n.text).includes(normal(r.match)))}
function read(){if(window.LATIN_NOTES)return window.LATIN_NOTES.read();try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}}
function write(n){if(window.LATIN_NOTES)return window.LATIN_NOTES.upsert(n);const notes=read(),i=notes.findIndex(x=>x.id===n.id);if(i<0)notes.push(n);else notes[i]=n;localStorage.setItem(key,JSON.stringify(notes));window.dispatchEvent(new Event('latin-notes-changed'))}
const launcher=document.createElement('button');launcher.className='notes-launcher';launcher.textContent='＋ Note';launcher.setAttribute('aria-label','Add a note about this page');document.body.append(launcher);
launcher.onclick=()=>{
 const dialog=document.createElement('dialog');dialog.className='notes-dialog';dialog.innerHTML='<header class="note-heading"><h2>Help improve this app</h2><button class="close-note" aria-label="Close notes">×</button></header><p>Tell us what confused you or what you want to keep.</p><label for="appNote">Your note</label><textarea id="appNote" rows="4" maxlength="4000"></textarea><label><input type="checkbox" id="devNote"> Developer note</label><p id="noteContext"></p><div class="actions"><button id="saveNote">Save note</button><button id="cancelEdit" hidden>Cancel edit</button></div><p id="noteStatus" role="status"></p><h3>Your notes</h3><p>Open notes first; implemented notes are ticked below. Draft notes are not automatically reviewed by AI.</p><div id="savedNotes"></div><footer><button id="doneNotes">Done</button></footer>';document.body.append(dialog);
 const input=dialog.querySelector('textarea'),status=dialog.querySelector('#noteStatus');let editing=null;
 const reset=()=>{editing=null;input.value='';dialog.querySelector('#devNote').checked=false;dialog.querySelector('#saveNote').textContent='Save note';dialog.querySelector('#cancelEdit').hidden=true;dialog.querySelector('#noteContext').textContent='Version '+version+' · '+(location.hash||'#home');};
 const render=()=>{const box=dialog.querySelector('#savedNotes');box.replaceChildren();const notes=read().sort((a,b)=>Number(!!resolution(a)||!!a.archived)-Number(!!resolution(b)||!!b.archived)||Date.parse(b.updatedAt||b.at)-Date.parse(a.updatedAt||a.at));
 for(const n of notes){const resolved=resolution(n),p=document.createElement('article');p.className='saved-note'+(resolved||n.archived?' note-complete':'');const title=document.createElement('strong');title.textContent=resolved?'✓ Implemented in '+resolved.version:n.archived?'Archived':'Open';p.append(title);const text=document.createElement('p');text.textContent=n.text;p.append(text);const meta=document.createElement('small');meta.textContent=n.version+' · '+n.page;p.append(meta);
 if(resolved){const a=document.createElement('a');a.href='#releases/'+resolved.id;a.textContent='Read what changed';a.onclick=()=>dialog.close();p.append(a)}
 const edit=document.createElement('button');edit.textContent='Edit';edit.onclick=()=>{editing=n;input.value=n.text;window.LATIN_NOTES?.draft(n.text,n.id);dialog.querySelector('#devNote').checked=!!n.developer;dialog.querySelector('#saveNote').textContent='Save changes';dialog.querySelector('#cancelEdit').hidden=false;input.focus();input.scrollIntoView({block:'center'})};p.append(edit);
 const archive=document.createElement('button');archive.textContent=n.archived?'Restore':'Archive';archive.onclick=()=>write({...n,archived:!n.archived,updatedAt:new Date().toISOString()});p.append(archive);
 const send=document.createElement('a');send.textContent='Review on GitHub';send.target='_blank';send.rel='noopener';send.href='https://github.com/'+repo+'/issues/new?title='+encodeURIComponent('[App feedback] '+n.text.slice(0,65))+'&body='+encodeURIComponent('Public app feedback — omit personal details.\nNote ID: '+n.id+'\nVersion: '+n.version+'\nPage: '+n.page+'\n\n'+n.text);p.append(send);box.append(p)}if(!notes.length)box.textContent='No notes yet.';
 };
 dialog.querySelector('#saveNote').onclick=()=>{if(!input.value.trim()){status.textContent='Write a note first.';input.focus();return}const now=new Date().toISOString(),n={...(editing||{}),id:editing?.id||crypto.randomUUID(),text:input.value.trim(),version:editing&&editing.text===input.value.trim()?editing.version:version,page:editing?.page||location.hash||'#home',developer:dialog.querySelector('#devNote').checked,at:editing?.at||now,updatedAt:now};try{write(n);reset();window.LATIN_NOTES?.draft('');status.textContent='Saved. '+(window.LATIN_NOTES?.status()||'Stored on this device.');render()}catch{status.textContent='Could not save. Keep this text and try again.'}};
 dialog.querySelector('#cancelEdit').onclick=reset;
 const close=()=>{if(input.value.trim())window.LATIN_NOTES?.draft(input.value);dialog.close()};
 dialog.querySelector('.close-note').onclick=close;dialog.querySelector('#doneNotes').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
 window.addEventListener('latin-notes-changed',render);dialog.addEventListener('close',()=>{window.removeEventListener('latin-notes-changed',render);dialog.remove()});reset();input.value=window.LATIN_NOTES?.getDraft()||'';const draftId=window.LATIN_NOTES?.getDraftId?.(),draft=window.LATIN_NOTES?.getDraft()||'';if(draftId){const found=read().find(n=>n.id===draftId);if(found){editing=found;dialog.querySelector('#saveNote').textContent='Save changes';dialog.querySelector('#cancelEdit').hidden=false}}input.value=draft;input.oninput=()=>window.LATIN_NOTES?.draft(input.value,editing?.id||null);render();dialog.showModal();input.focus();
};
